openapi: 3.1.0
info:
  title: Tripi Pro API
  version: "1.0.0"
  description: |
    Plan multi-day travel itineraries between two cities.
    POST /api/plan returns polyline, start/end, distanceText, durationText, and POIs.

servers:
  - url: "https://tripi-pro.vercel.app"

paths:
  /api/plan:
    post:
      summary: Create a trip plan
      description: >
        Generate a multi-day route and POIs between origin and destination.
      operationId: createPlan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: string
                  example: 台北
                destination:
                  type: string
                  example: 墾丁
                days:
                  type: integer
                  minimum: 1
                  maximum: 14
                  example: 5
              required: [origin, destination, days]
      responses:
        "200":
          description: Plan generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  provider:
                    type: string
                    enum: [google, osrm]
                  polyline:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                      minItems: 2
                      maxItems: 2
                  start:
                    type: object
                    properties:
                      lat: { type: number }
                      lng: { type: number }
                      address: { type: string }
                  end:
                    type: object
                    properties:
                      lat: { type: number }
                      lng: { type: number }
                      address: { type: string }
                  distanceText: { type: string }
                  durationText: { type: string }
                  pois:
                    type: array
                    items:
                      type: object
                      properties:
                        name: { type: string }
                        lat: { type: number }
                        lng: { type: number }
                        address: { type: string }
                        rating: { type: number }
        "400":
          description: Bad request
        "500":
          description: Server error
